name: 'MAIN'
runs:
  using: 'composite'
  steps:

    - name: MAIN - Add staticwebapp.config.json
      run: |
        mv json/azure-ritsafn-main/staticwebapp.config.json rit/_build/html/
      shell: bash

    - name: MAIN - Add robots.txt
      run: |
        mv txt/robots.txt rit/_build/html/
      shell: bash