name: 'DEV'
runs:
  using: 'composite'
  steps:

    - name: DEV - Build Sphinx documentation
      run: |
        sh/build-dev-dirhtml-latexpdf.sh
      shell: bash

    - name: DEV - Add staticwebapp.config.json
      run: |
        mv json/azure-ritsafn-dev/staticwebapp.config.json rit/_build/html/
      shell: bash

    - name: DEV - Add meta tag to HTML
      run: |
        find rit/_build/html -name '*.html' -exec sed -i 's/<head>/<head>\n    <meta name="robots" content="noindex, nofollow">/' {} +
      shell: bash

    - name: DEV - Delete sitemap.xml
      run: |
        rm rit/_build/html/sitemap.xml
      shell: bash