name: 'DEV'
runs:
  using: 'composite'
  steps:

    - name: DEV - Build Sphinx documentation
      run: |
        sh/build-dev-dirhtml-latexpdf.sh
      shell: bash

    - name: DEV - Add staticwebapp.config.json
      run: |
        mv json/azure-ritsafn-dev/staticwebapp.config.json rit/_build/html/
      shell: bash

    - name: DEV - Add favicon files
      run: |
        mv json/webmanifest.json rit/_build/html/
        mv rit/_static/favicon/favicon.ico rit/_build/html/
        mv rit/_static/favicon/icon.svg rit/_build/html/
        mv rit/_static/favicon/apple-touch-icon.png rit/_build/html/
        mv rit/_static/favicon/icon-192.png rit/_build/html/
        mv rit/_static/favicon/icon-512.png rit/_build/html/
      shell: bash

    - name: DEV - Delete sitemap.xml
      run: |
        rm rit/_build/html/sitemap.xml
      shell: bash