name: 'ALL'
runs:
  using: 'composite'
  steps:

    - name: ALL - Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.3'

    - name: ALL - Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r txt/requirements.txt
      shell: bash

    - name: ALL - Install LaTeX dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive texlive-latex-extra latexmk texlive-fonts-recommended dvipng pdf2svg texlive-lang-european
      shell: bash

    - name: ALL - Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: ALL - Install Prettier
      run: npm install --global prettier
      shell: bash

    - name: Install sed (if needed)
      run: sudo apt-get install -y sed
      shell: bash

    - name: ALL - Build Sphinx documentation
      run: |
        ./makesphinx.sh
      shell: bash