name: 'ALL'
runs:
  using: 'composite'
  steps:

    - name: ALL - Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.3'

    - name: ALL - Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash

    - name: ALL - Install LaTeX dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive texlive-latex-extra latexmk texlive-fonts-recommended dvipng pdf2svg texlive-lang-european
      shell: bash

    - name: ALL - Build Sphinx documentation
      run: |
        cd rit
        make clean
        make html
        make latexpdf
        mv _build/latex/*.pdf _build/html/
        for dir in */ ; do
          if [[ -d "$dir" && "$dir" != _* ]]; then
            cd "$dir"
            make clean
            make latexpdf
            mv _build/latex/*.pdf "../_build/html/${dir%/}/"
            cd ..
          fi
        done
      shell: bash