name: 'ALL'
runs:
  using: 'composite'
  steps:

    - name: ALL - Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.3'

    - name: ALL - Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash

    - name: ALL - Install LaTeX dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive texlive-latex-extra latexmk texlive-fonts-recommended dvipng pdf2svg texlive-lang-european
      shell: bash

    - name: ALL - Build Sphinx documentation
      run: |
        cd rit
        make clean
        make html
        make latexpdf
        mv _build/latex/Ritsafn-RÚBIK-Reykjavíkur--Öll-rit-sameinuð.pdf _build/html/
        cd rit/fjarmal-einstaklinga
        make clean
        make latexpdf
        mv _build/latex/Ritsafn-RÚBIK-Reykjavíkur--Fjármál-einstaklinga.pdf ../_build/html/fjarmal-einstaklinga/
        cd rit/fjarmal-fyrirtaekja
        make clean
        make latexpdf
        mv _build/latex/Ritsafn-RÚBIK-Reykjavíkur--Fjármál-fyrirtækja.pdf ../_build/html/fjarmal-fyrirtaekja/
        cd rit/kitchen-sink
        make clean
        make latexpdf
        mv _build/latex/Ritsafn-RÚBIK-Reykjavíkur--Kitchen-sink.pdf ../_build/html/kitchen-sink/
      shell: bash