name: 'MAIN'
runs:
  using: 'composite'
  steps:

    - name: MAIN - Build Sphinx documentation
      run: |
        sh/build-main-dirhtml-latexpdf.sh
      shell: bash

    - name: MAIN - Add staticwebapp.config.json
      run: |
        mv json/azure-ritsafn-main/staticwebapp.config.json rit/_build/html/
      shell: bash

    - name: MAIN - Add robots.txt
      run: |
        mv txt/robots.txt rit/_build/html/
      shell: bash

    - name: MAIN - Add favicon files
      run: |
        mv json/webmanifest.json rit/_build/html/
        mv rit/_static/favicon/favicon.ico rit/_build/html/
        mv rit/_static/favicon/icon.svg rit/_build/html/
        mv rit/_static/favicon/apple-touch-icon.png rit/_build/html/
        mv rit/_static/favicon/icon-192.png rit/_build/html/
        mv rit/_static/favicon/icon-512.png rit/_build/html/
      shell: bash