name: DEV - Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - dev

jobs:

  build_and_deploy_job:

    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: DEV - Build and Deploy Job
    steps:

      - name: ALL - Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: ALL
        uses: ./yml/azure-ritsafn-all

      - name: DEV
        uses: ./yml/azure-ritsafn-dev

      - name: DEV - Build And Deploy
        id: dev-builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_COAST_0C606EF03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "rit/_build/html"
          api_location: ""
          output_location: ""

  close_pull_request_job:

    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: DEV - Close Pull Request Job
    steps:

      - name: DEV - Close Pull Request
        id: dev-closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_COAST_0C606EF03 }}
          action: "close"
